### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by tjingboem** [ales-tsurko/athenaCL#1]
Hi Ales,

i am glad that you are taking care of AthenaCl now and have updated it to be used with python 3.
i was trying to install the program but got an error- seems like something is missing...

Can you have a look when you have the time?
I am working with Linux Mint
thanks,
Menno

menno@mennoASUSZ170 ~/athenaCL $ sudo python3 setup.py install
setup.py: active athenaCL package directory: /home/menno/athenaCL 
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/athenaCL
copying athenaCL/__init__.py -> build/lib/athenaCL
copying athenaCL/athenacl.py -> build/lib/athenaCL
creating build/lib/athenaCL/demo
copying athenaCL/demo/__init__.py -> build/lib/athenaCL/demo
creating build/lib/athenaCL/demo/csound
copying athenaCL/demo/csound/script03e.py -> build/lib/athenaCL/demo/csound
copying athenaCL/demo/csound/script02b.py -> build/lib/athenaCL/demo/csound
copying athenaCL/demo/csound/script01d.py -> build/lib/athenaCL/demo/csound
copying athenaCL/demo/csound/script03a.py -> build/lib/athenaCL/demo/csound
copying athenaCL/demo/csound/script01c.py -> build/lib/athenaCL/demo/csound
copying athenaCL/demo/csound/__init__.py -> build/lib/athenaCL/demo/csound
copying athenaCL/demo/csound/script02a.py -> build/lib/athenaCL/demo/csound
copying athenaCL/demo/csound/script03b.py -> build/lib/athenaCL/demo/csound
copying athenaCL/demo/csound/script01b.py -> build/lib/athenaCL/demo/csound
copying athenaCL/demo/csound/script03c.py -> build/lib/athenaCL/demo/csound
copying athenaCL/demo/csound/script01a.py -> build/lib/athenaCL/demo/csound
copying athenaCL/demo/csound/script03d.py -> build/lib/athenaCL/demo/csound
creating build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script02b.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script07a.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script03a.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script06a.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/__init__.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script02a.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script09b.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script02f.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script03b.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script01b.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script02d.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script04b.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script09c.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script03c.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script05c.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script02g.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script08c.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script05a.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script07b.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script09a.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script01a.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script08d.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script09d.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script02c.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script10b.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script08b.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script10a.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script04a.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script02e.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script08a.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script04c.py -> build/lib/athenaCL/demo/midi
copying athenaCL/demo/midi/script05b.py -> build/lib/athenaCL/demo/midi
creating build/lib/athenaCL/demo/legacy
copying athenaCL/demo/legacy/__init__.py -> build/lib/athenaCL/demo/legacy
error: package directory 'athenaCL/demo/manual' does not exist

**Comment by ales-tsurko** [comment]
Thanks for the report. Should work now.

**Comment by tjingboem** [comment]
not yet - sorry

menno@mennoASUSZ170 ~ $ sudo python3 /home/menno/athenaCL-master/setup.py install
setup.py: cwd (/home/menno) is not the athenaCL src directory (/home/menno/athenaCL-master/athenaCL) 
setup.py: active athenaCL package directory: /home/menno 
running install
running build
running build_py
error: package directory 'athenaCL' does not exist

**Comment by tjingboem** [comment]
also renaming athenaCL-master to AthenaCL did not work:

menno@mennoASUSZ170 ~ $ sudo python3 /home/menno/athenaCL/setup.py install
setup.py: cwd (/home/menno) is not the athenaCL src directory (/home/menno/athenaCL/athenaCL) 
setup.py: active athenaCL package directory: /home/menno 
running install
running build
running build_py
package init file 'athenaCL/__init__.py' not found (or not a regular file)
copying athenaCL/setup.py -> build/lib/athenaCL
error: package directory 'athenaCL/demo' does not exist

**Comment by tjingboem** [comment]
okay it works, my fault

**Comment by tjingboem** [comment]
the install command 'tool' added a command  to my Linux Mint sytem:

menno@mennoASUSZ170 ~/athenaCL $ sudo python3 setup.py tool
setup.py: active athenaCL package directory: /home/menno/athenaCL 
setup.py: writing launcher script:
/home/menno/athenaCL/athenaCL/athenacl.py 
setup.py installing launcher script:
/usr/local/bin/athenacl
moving /usr/local/bin/athenacl: (user password required).
setup.py: copying manual-page file 
writing /usr/share/man/man1/athenacl.1: (user password required).
cp: cannot stat '/home/menno/athenaCL/doc/athenacl.1': No such file or directory
setup.py: complete
 
menno@mennoASUSZ170 ~/athenaCL $ athenacl 

athenaCL 2.0.0a15 (on linux via terminal)
Enter "cmd" to see all commands. For help enter "?".
Enter "c" for copyright, "w" for warranty, "r" for credits.

pi{}ti{} :: q
exit athenaCL? (y or n): y


thanks for your work, i will continue with testing now :)

**Comment by ales-tsurko** [comment]
Thanks!

> i will continue with testing now 

👍
