### ISSUE TITLE
TImap may not work

### ISSUE THREAD

**Issue by ales-tsurko** [ales-tsurko/athenaCL#2]
As reported by email:

> i tested the program today, and i see some of the options are not possible (anymore), like TImap that requires Python Image Library. This is only available for Python2...

**Comment by ales-tsurko** [comment]
This is fixed by using [Pillow](https://python-pillow.org/) instead.

**Comment by tjingboem** [comment]
While perhaps this is working on a Mac, i don't see it working on Linux Mint.
I did install willow- that installed the pillow lib:  pillow.py in /usr/lib/python3/dist-packages/willow/plugins

I don't know if you care to support athenaCL on Linux?

**Comment by ales-tsurko** [comment]
I've made some changes related to this, try again. Also, if you'll still have this bug, please describe the steps to reproduce it and the result you get. And to be sure it's not related to installation, try it with a separated pillow install instead.

**Comment by tjingboem** [comment]
still no luck i'm afraid...i hope it is not user error
but here are the steps i took:

menno@mennoASUSZ170 /media/menno/datae/temp2/athenaCL-master $ athenacl

athenaCL 2.0.0a15 (on linux via terminal)
Enter "cmd" to see all commands. For help enter "?".
Enter "c" for copyright, "w" for warranty, "r" for credits.

pi{}ti{} :: tin
name this texture: a
enter any instrument number: 1
provide number of auxiliary parameters: 0
TI a created.

pi{auto}ti{a} :: tiv
TI: a, TM: LineGroove, TC: 0, TT: TwelveEqual
pitchMode: pitchSpace, silenceMode: off, postMapMode: on
midiProgram: piano1
      status: +, duration: ?--?
(i)nstrument        1 (csoundExternal: generic)                                                                          
(t)ime range        00.0--20.0                                                                                           
(b)pm               constant, 120                                                                                        
(r)hythm            pulseTriple, (constant, 4), (basketGen, randomPermutate, (1,1,2,3)), (constant, 1), (constant, 0.75) 
(p)ath              auto                                                                                                 
                    (C4)                                                                                                 
                    20.00(s)                                                                                             
local (f)ield       constant, 0                                                                                          
local (o)ctave      constant, 0                                                                                          
(a)mplitude         randomBeta, 0.4, 0.4, (constant, 0.7), (constant, 0.9)                                               
pan(n)ing           constant, 0.5                                                                                        
au(x)iliary         none                                                                                                 
texture (s)tatic                                                                                                         
      s0            parallelMotionList, (), 0.0                                                                          
      s1            pitchSelectorControl, randomPermutate                                                                
      s2            levelFieldMonophonic, event                                                                          
      s3            levelOctaveMonophonic, event                                                                         
texture (d)ynamic   none                                                                                                 

pi{auto}ti{a} :: timap
TImap (event-base, pre-TM) display complete.

pi{auto}ti{a} :: ausys
athenaCL system:
..............................................................................................................................................................................................................................................
athenaCL version:             2.0.0-a15.2010.07.07                                   
python version:               3.8.5.final                                            
os name, sys platform:        posix.linux                                            
..............................................................................................................................................................................................................................................
SC dictionary mode:           Tn                                                     
current PathInstance:         auto                                                   
total PI:                     1                                                      
current TextureModule:        LineGroove                                             
current TextureInstance:      a                                                      
total TI:                     1                                                      
total duration:               20.1                                                   
..............................................................................................................................................................................................................................................
current EventMode:            csoundExternal                                         
current EventOutput formats:  midiFile,xmlAthenaObject,csoundData                    
EventMode auto render:        off                                                    
audio channels:               2                                                      
audio file format:            aif                                                    
midi tempo:                   120                                                    
..............................................................................................................................................................................................................................................
dialog method:                text                                                   
graphics format:              png                                                    
refresh mode:                 off                                                    
..............................................................................................................................................................................................................................................
preferences:                  /home/menno/.athenaclrc                                
log:                          /home/menno/.athenacl-log                              
user scratch:                 /media/menno/datae/temp                                
user audio:                                                                          
libATH:                       /usr/local/lib/python3.8/dist-packages/athenaCL/libATH 
working directory:            /media/menno/datae/temp2/athenaCL-master               
python executable:            /usr/bin/python3                                       
python site:                  /usr/lib/python3.8                                     
midi player:                  /usr/bin/vlc                                           
audio player:                 /usr/bin/vlc                                           
text reader:                  more                                                   
image viewer:                 /usr/bin/xviewer                                       
postscript viewer:            gs                                                     
csound path:                  /usr/local/bin/csound                                  

pi{auto}ti{a} ::

**Comment by tjingboem** [comment]
yep- works!
thank you very much!
